name: Deploy Nginx

on:
  push:
    branches:
    - 'main'
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v4		
      
    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true
    
    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run:
        gcloud auth configure-docker europe-west8-docker.pkg.dev
    - name: Build
      run: |-
        docker build -t europe-west8-docker.pkg.dev/${{GOOGLE_PROJECT}}/demo/nginx:latest .
    - name: Publish
      run: |-
        docker push europe-west8-docker.pkg.dev/${{GOOGLE_PROJECT}}/demo/nginx:latest

        